version: '3.8'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "8081:8081"  ## левый во вне, правый в контейнере
    expose:
      - 8081
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_TCP_PORT: 8081


#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"

  mocker:
    build: .
    container_name: mocker
    command: python app.py
    depends_on:
      - db
    ports:
      - "8082:8082"
    restart: always
